// I am not too sure if this file is necessary, might remove

#define AL_IMPORT(fun, t) t fun
#include "EFXImports.h"
#undef AL_IMPORT

AL_IMPORT(alGenEffects, LPALGENEFFECTS);
AL_IMPORT(alDeleteEffects, LPALDELETEEFFECTS);
AL_IMPORT(alIsEffect, LPALISEFFECT);
AL_IMPORT(alEffecti, LPALEFFECTI);
AL_IMPORT(alEffectiv, LPALEFFECTIV);
AL_IMPORT(alEffectf, LPALEFFECTF);
AL_IMPORT(alEffectfv, LPALEFFECTFV);
AL_IMPORT(alGetEffecti, LPALGETEFFECTI);
AL_IMPORT(alGetEffectiv, LPALGETEFFECTIV);
AL_IMPORT(alGetEffectf, LPALGETEFFECTF);
AL_IMPORT(alGetEffectfv, LPALGETEFFECTFV);

AL_IMPORT(alGenFilters, LPALGENFILTERS);
AL_IMPORT(alDeleteFilters, LPALDELETEFILTERS);
AL_IMPORT(alIsFilter, LPALISFILTER);
AL_IMPORT(alFilteri, LPALFILTERI);
AL_IMPORT(alFilteriv, LPALFILTERIV);
AL_IMPORT(alFilterf, LPALFILTERF);
AL_IMPORT(alFilterfv, LPALFILTERFV);
AL_IMPORT(alGetFilteri, LPALGETFILTERI);
AL_IMPORT(alGetFilteriv, LPALGETFILTERIV);
AL_IMPORT(alGetFilterf, LPALGETFILTERF);
AL_IMPORT(alGetFilterfv, LPALGETFILTERFV);

AL_IMPORT(alGenAuxiliaryEffectSlots, LPALGENAUXILIARYEFFECTSLOTS);
AL_IMPORT(alDeleteAuxiliaryEffectSlots, LPALDELETEAUXILIARYEFFECTSLOTS);
AL_IMPORT(alIsAuxiliaryEffectSlot, LPALISAUXILIARYEFFECTSLOT);
AL_IMPORT(alAuxiliaryEffectSloti, LPALAUXILIARYEFFECTSLOTI);
AL_IMPORT(alAuxiliaryEffectSlotiv, LPALAUXILIARYEFFECTSLOTIV);
AL_IMPORT(alAuxiliaryEffectSlotf, LPALAUXILIARYEFFECTSLOTF);
AL_IMPORT(alAuxiliaryEffectSlotfv, LPALAUXILIARYEFFECTSLOTFV);
AL_IMPORT(alGetAuxiliaryEffectSloti, LPALGETAUXILIARYEFFECTSLOTI);
AL_IMPORT(alGetAuxiliaryEffectSlotiv, LPALGETAUXILIARYEFFECTSLOTIV);
AL_IMPORT(alGetAuxiliaryEffectSlotf, LPALGETAUXILIARYEFFECTSLOTF);
AL_IMPORT(alGetAuxiliaryEffectSlotfv, LPALGETAUXILIARYEFFECTSLOTFV);